### PR TITLE
Adds ErrorMessage, Char, IntMap, Map and Set instances

### PR DESCRIPTION
**Pull request by Skyfold**
Two important changes:

1. I added instances to IntMap, Map and Set to convert directly from `'[a]` or `'[ '(key,val) ]`
2. I removed `KnownNats`

I'm not sure what you wanted to use `KnownNats` for since `KnownVal` handled those cases. I thought it would be less confusing to just have one type class. At the same time, I am removing a class you wrote. If you want to keep it there, let me know and I'll put it back in the PR.

The `ErrorMessage` instance I wanted so I could show all of my types.

### CODE REVIEW

**Comment by gspia** [comment]
The `KnownNats` was just a left over - I first needed to get a list of numbers to value (before there were any thoughts about `KnownVal` type class. It has been there now maybe couple of months, so I wonder if there would be any users who would see this as a breaking change. 

Maybe I'll just warn people clearly enough when publishing the next version, as it would be more clear and better to use the `KnownVal`  than to continue using the `KnownNats`. The `KnownNats` is simple and small and if some people still would like to continue using, it is easy to bring it back as well or they might could just copy the implementation to their side.

**Comment by gspia** [comment]
Thanks for fixing the pipeline problem before I had a chance to ask about it!

**Comment by Skyfold** [comment]
> The `KnownNats` was just a left over - I first needed to get a list of numbers to value (before there were any thoughts about `KnownVal` type class. It has been there now maybe couple of months, so I wonder if there would be any users who would see this as a breaking change.
> 
> Maybe I'll just warn people clearly enough when publishing the next version, as it would be more clear and better to use the `KnownVal` than to continue using the `KnownNats`. The `KnownNats` is simple and small and if some people still would like to continue using, it is easy to bring it back as well or they might could just copy the implementation to their side.

I'll put it back in with a deprecated warning and then we can remove it a few releases latter.

**Comment by gspia** [comment]
Cool and thanks! Process-wice it is better of course to have that deprecation notice included and this way it is better for those who use it (if any). (I was already ready to just take that change in right now.)

I also like the idea of being able to convert directly from some other types. Somehow, I feel that oftentimes on type/kind level we need to model data types "indirectly" compared to what we would normally do. And e.g. the current `Set` implementation is sub-optimal performance-wice, which means that depending on situation, people might need to actually use other structures that are meant to be `Set` but for some reasons they just have to use other structures for it like lists. Then on value level, continue with the `Set` from containers.

**Pull request merged**
