### PR TITLE
Adds Tuple instances to Monad, Applicative and Traversable

### PR DESCRIPTION
**Pull request by Skyfold**
I also added: 
- replaced instances for `>>` and `liftA2` with a single "default" instance
- Some tests for Applicative, Monad and Traversable (Its just a start)
- Some reorganization of the code in `Fcf.Control.Monad` to make the haddocks easier to read. (In reality I should just make the exports explicit)

Before I add any more tests or set exports to organize the generated haddocks, I wanted to get some feedback on how you want to organize the codebase.

### CODE REVIEW

**Comment by Skyfold** [comment]
I also added a flake.nix based on what I use in my other projects (you can still use the default.nix). If you want to switch to using flakes I would recommend we use https://haskell.flake.page/ (I have been meaning to try it out).

**Comment by gspia** [comment]
> If you want to switch to using flakes I would recommend we use https://haskell.flake.page/ 

Thanks, I'll take a look as well. I've been using the same way to make my projects and only recently switched to flakes based setups on my servers.

I wonder, hows Srid's flake is different from iohk one: https://github.com/input-output-hk/haskell.nix/blob/master/docs/tutorials/getting-started-flakes.md (they refer to `templates#haskell-nix --impure`). And looks like that there is another one coming from serokell: https://serokell.io/blog/practical-nix-flakes (they refer to `github:serokell/templates#haskell-cabal2nix`)

**Comment by Skyfold** [comment]
I added the tests for liftA3 and liftA2 in `Test.Data.Reflect`. I think comparing the type level directly with their value level counterparts makes more sense than the `Refl` tests I wrote in `test/test.hs`.

Do you want to have separate test files for each module? For example: `Fcf.Control.Monad` would have `Fcf.Control.MonadTest`.

**Comment by Skyfold** [comment]
> > If you want to switch to using flakes I would recommend we use https://haskell.flake.page/
> 
> Thanks, I'll take a look as well. I've been using the same way to make my projects and only recently switched to flakes based setups on my servers.
> 
> I wonder, hows Srid's flake is different from iohk one: https://github.com/input-output-hk/haskell.nix/blob/master/docs/tutorials/getting-started-flakes.md (they refer to `templates#haskell-nix --impure`). And looks like that there is another one coming from serokell: https://serokell.io/blog/practical-nix-flakes (they refer to `github:serokell/templates#haskell-cabal2nix`)

I'm not a fan of iohk simply because they are not based on the haskell tooling in nixpkgs, so you need to use their binary cache (or run your own). If you need to also support stack this is your best option, but I have found stack based projects are difficult to build with nix since they use packages sets with different versions than nixpkgs. (Note: stack is currently the best way to test out multiple versions of GHC if you want to support more GHC versions than what nixpkgs provides in a single commit, [link](https://www.extrema.is/blog/2021/08/22/testing-ghc-versions))

The serokell flake.nix looks fine (although a bit messy), but makes it hard to have multiple GHC versions without editing the file each time you want to test out another GHC version.

I like that Srid's has a way to easy add multiple projects (each with their own GHC version). They don't have an example of testing a library with multiple versions, but you can always bring in all versions of GHC like in this [link](https://qfpl.io/posts/multiple-ghcs/).

**Comment by gspia** [comment]
> I added the tests for liftA3 and liftA2 in `Test.Data.Reflect`. I think comparing the type level directly with their value level counterparts makes more sense than the `Refl` tests I wrote in `test/test.hs`.

Ok, sounds reasonable!
 
> Do you want to have separate test files for each module? For example: `Fcf.Control.Monad` would have `Fcf.Control.MonadTest`.

Yes, this way (roughly), a separate test file for each module makes it easier to find out the test cases of a module. About the namings of test files (or test modules). In this example, I've been used to `Test.Fcf.Control.Monad` on the work projects. That has been due to the extra "Test" directory under "test", or, using `<libroot>/test/Test/Control/Monad.hs` path. Often, the actual test executable has been something like `<libroot>/test/testMain.hs`.

I wonder, if it would be ok (in the long run) to just use `<libroot>/test/Control/Monad.hs` and `<libroot>/test/testMain.hs`. This way, the test module path would be exactly the same as actual module path. I probably have to try if there are any suprises with this approach, and if not, then maybe use this. 

Anyhow, I don't have big opinions on this matter. Just trying to get a bit closer 1-1 correspondence between tests and code side.

**Comment by gspia** [comment]
> I'm not a fan of iohk simply because they are not based on the haskell tooling in nixpkgs, so you need to use their binary cache (or run your own). ...

Yes, and now I remember that this has prevented me to try their flakes earlier when I wondered these.

> The serokell flake.nix looks fine (although a bit messy), but makes it hard to have multiple GHC versions without editing the file each time you want to test out another GHC version.

Ok, good to know. I haven't considered using serokell earlier. At the moment my plain nix way to try with different ghc versions has been to start a separate shell for trials and tests and in between, edit the `default.nix`. (Not very good approach, or at least tedious. Sometimes, the nix-shell wants to build ghc and I've been trying to avoid doing that for several versions at the same time.)
 
> I like that Srid's has a way to easy add multiple projects (each with their own GHC version). 

:+1: sounds good! I'll read the docs Srid has written and play with it!

> They don't have an example of testing a library with multiple versions, but you can always bring in all versions of GHC like in this [link](https://qfpl.io/posts/multiple-ghcs/).

Again, something for me to try out. Thanks for the link! I probably want to avoid several massive local ghc buildings happening at the same time, but let's see.

**Comment by Skyfold** [comment]
This commit is a bit more involved, let me know if I'm overstepping with my changes. Also, feel free to question/comment/change what I have written.

1. Setup test hierarchy like `<libroot>/test/Test/Control/Monad.hs `
2. Added `hspec` so I could figure out which test was failing.
3. Migrated all tests to use `hspec`
4. Changed `KnownVal` variable order and generalized the instances

The last change needs some explanation. 

I switched the variables from `class KnownVal typeval val` to `class KnownVal val kind`.
- This lets me write `fromType @Int (Proxy @Nat)`
- Instead of `fromType @Nat Proxy :: Int` or `fromType @Nat @Int Proxy`.

Since the `Proxy` is there to pass around the kind information, it makes sense the first type application is for the value instead of repeating what the `Proxy` provides.

**Comment by gspia** [comment]
>     1. Setup test hierarchy like `<libroot>/test/Test/Control/Monad.hs `
>     2. Added `hspec` so I could figure out which test was failing.
>     3. Migrated all tests to use `hspec`

Thank you very much for these! This is quite close to what I probably would have done as well next. Now it is easier to just follow the pattern with other modules and I hope to get doing that soon(ish).


>     4. Changed `KnownVal` variable order and generalized the instances

Thanks for these! I also was trying one way to try to generalize the `KnownVal` and I was studying different possibilities. Basically, the goal here is to allow "multiple layers of data types" to be reflected to value level (`[[Just 1, Just2]]` and similar constructs). I had some difficulties there, especially with `Maybe` and `Either` instances. Anyhow, I also already started to implement a very dump but most likely a working method. 

I'll take these in and I'll try to get the next version published reasonably soon.

**Pull request merged**
